name: PR Tests

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main

jobs:
  test:
#   Note: We run on macos-latest so that the screenshots have
#         the same os in the file names and can be compared on in the pipeline.
#         There is still a discrepancy in the rendering, we may need to use docker
#         to run --update-snapshots so that we can use identical os.
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright
        run: pnpm exec playwright install --with-deps

      - name: Build Packages
        run: pnpm lerna:build

      - name: Run Stencil Checks
        run: | 
          cd packages/stencil-library
          pnpm check

      - name: Run Stencil Spec Tests
        run: | 
          cd packages/stencil-library
          pnpm test:spec

      - name: Run Stencil e2e Tests
        run: | 
          cd packages/stencil-library
          pnpm test:e2e

      - name: Run React e2e Tests
        run: | 
          cd packages/react-client
          pnpm test:e2e

#      1. create new branch
#      2. version (updates the package.json versions) 0.0.1 current after version 0.0.2
#      3. commit to branch
#      4. push to branch
#      5. create PR to main from new branch
#      6. possibly push tags now (or in publish step)
#      7. (NO) possibly auto merge pr (needs admin/special github personal access token permissions)

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: stencil-playwright-report
          path: packages/stencil-library/playwright-report/
          retention-days: 30

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: react-playwright-report
          path: packages/react-client/playwright-report/
          retention-days: 30
