name: PR Tests

on:
  pull_request:
    types: [ opened, synchronize ]
    branches:
      - main

jobs:
  test:
    # Note: We run on macos-latest so that the screenshots have
    #       the same os in the file names and can be compared on in the pipeline.
    #       There is still a discrepancy in the rendering, we may need to use docker
    #       to run --update-snapshots so that we can use identical os.
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Install Playwright
        run: pnpm exec playwright install --with-deps

      - name: Build Packages
        run: export NODE_ENV=test && pnpm lerna:build # export NODE_ENV=test tells rollup dotenv to read from .env.test

      - name: Run Stencil Checks
        run: | 
          cd packages/web-components
          pnpm check

      - name: Run Stencil Spec Tests
        run: | 
          cd packages/web-components
          pnpm test:spec

      - name: Run Stencil e2e Tests
        run: | 
          cd packages/web-components
          pnpm test:e2e
        env:
          TEST_STRIPE_KEY: ${{ secrets.TEST_STRIPE_KEY }}
          TEST_STRIPE_ACCOUNT_ID: ${{ secrets.TEST_STRIPE_ACCOUNT_ID }}
          TEST_STRIPE_CUSTOMER_ID: ${{ secrets.TEST_STRIPE_CUSTOMER_ID }}
          TEST_STRIPE_PLAN_ID: ${{ secrets.TEST_STRIPE_PLAN_ID }}

      - name: Run React e2e Tests
        run: | 
          cd packages/react-client
          pnpm test:e2e
        env:
          TEST_STRIPE_KEY: ${{ secrets.TEST_STRIPE_KEY }}
          TEST_STRIPE_ACCOUNT_ID: ${{ secrets.TEST_STRIPE_ACCOUNT_ID }}
          TEST_STRIPE_CUSTOMER_ID: ${{ secrets.TEST_STRIPE_CUSTOMER_ID }}
          TEST_STRIPE_PLAN_ID: ${{ secrets.TEST_STRIPE_PLAN_ID }}

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: stencil-playwright-report
          path: packages/web-components/playwright-report/
          retention-days: 7

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: react-playwright-report
          path: packages/react-client/playwright-report/
          retention-days: 7
