name: Docs Sync

on:
  push:
    branches:
      - main
    paths:
      - packages/docs/**
  workflow_dispatch:

jobs:
  docs_sync:
    name: Docs Sync
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      ADMIN_GH_PAT: ${{ secrets.ADMIN_GH_PAT }}
      SOURCE_DIR: ./packages/docs
      TARGET_DIR: ./docs/web-components

    steps:
      - name: Check out ${{ env.TARGET_DIR }}
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          path: ./

      - name: Check out docs
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          repository: salable/docs
          path: ./docs
          token: ${{ secrets.ADMIN_GH_PAT }}

      - name: List Docs (DEBUGGING)
        run: ls ./docs

      - name: Migrate Code to docs repo
        run: |
          # Remove the old folders in the docs repo
          rm -rf ${{ env.TARGET_DIR }}
                    
          # Move in the new folders
          mv ${{ env.SOURCE_DIR }}/docs ${{ env.TARGET_DIR }}

          # Commit the changes
          cd ./docs
          git config user.name "Salable App"
          git config user.email "<dev@salable.app>"
          git config --global credential.helper cache
          git add ${{ env.TARGET_DIR }}
          git status
          git commit -m "docs: synced with ${{ env.TARGET_DIR }} documentation"
          git push
