/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { StatusType } from "./components/common/salable-status/salable-status";
export { StatusType } from "./components/common/salable-status/salable-status";
export namespace Components {
    interface SalableButton {
    }
    interface SalableDate {
        "date": string | number;
    }
    interface SalableInvoices {
        "apiKey": string;
        "limit": number;
        "subscriptionUuid": string;
    }
    interface SalableSearch {
    }
    interface SalableStatus {
        "statusType": StatusType;
    }
}
declare global {
    interface HTMLSalableButtonElement extends Components.SalableButton, HTMLStencilElement {
    }
    var HTMLSalableButtonElement: {
        prototype: HTMLSalableButtonElement;
        new (): HTMLSalableButtonElement;
    };
    interface HTMLSalableDateElement extends Components.SalableDate, HTMLStencilElement {
    }
    var HTMLSalableDateElement: {
        prototype: HTMLSalableDateElement;
        new (): HTMLSalableDateElement;
    };
    interface HTMLSalableInvoicesElement extends Components.SalableInvoices, HTMLStencilElement {
    }
    var HTMLSalableInvoicesElement: {
        prototype: HTMLSalableInvoicesElement;
        new (): HTMLSalableInvoicesElement;
    };
    interface HTMLSalableSearchElement extends Components.SalableSearch, HTMLStencilElement {
    }
    var HTMLSalableSearchElement: {
        prototype: HTMLSalableSearchElement;
        new (): HTMLSalableSearchElement;
    };
    interface HTMLSalableStatusElement extends Components.SalableStatus, HTMLStencilElement {
    }
    var HTMLSalableStatusElement: {
        prototype: HTMLSalableStatusElement;
        new (): HTMLSalableStatusElement;
    };
    interface HTMLElementTagNameMap {
        "salable-button": HTMLSalableButtonElement;
        "salable-date": HTMLSalableDateElement;
        "salable-invoices": HTMLSalableInvoicesElement;
        "salable-search": HTMLSalableSearchElement;
        "salable-status": HTMLSalableStatusElement;
    }
}
declare namespace LocalJSX {
    interface SalableButton {
    }
    interface SalableDate {
        "date"?: string | number;
    }
    interface SalableInvoices {
        "apiKey"?: string;
        "limit"?: number;
        "subscriptionUuid"?: string;
    }
    interface SalableSearch {
    }
    interface SalableStatus {
        "statusType"?: StatusType;
    }
    interface IntrinsicElements {
        "salable-button": SalableButton;
        "salable-date": SalableDate;
        "salable-invoices": SalableInvoices;
        "salable-search": SalableSearch;
        "salable-status": SalableStatus;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "salable-button": LocalJSX.SalableButton & JSXBase.HTMLAttributes<HTMLSalableButtonElement>;
            "salable-date": LocalJSX.SalableDate & JSXBase.HTMLAttributes<HTMLSalableDateElement>;
            "salable-invoices": LocalJSX.SalableInvoices & JSXBase.HTMLAttributes<HTMLSalableInvoicesElement>;
            "salable-search": LocalJSX.SalableSearch & JSXBase.HTMLAttributes<HTMLSalableSearchElement>;
            "salable-status": LocalJSX.SalableStatus & JSXBase.HTMLAttributes<HTMLSalableStatusElement>;
        }
    }
}
