/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { StatusType } from "./enums/status-type";
export { StatusType } from "./enums/status-type";
export namespace Components {
    /**
     * button component
     */
    interface SalableButton {
    }
    interface SalableDate {
        /**
          * The date to display
         */
        "date": string | number;
    }
    interface SalableInvoices {
        /**
          * The publishable api key, this can be generated in the Salable dashboard
         */
        "apiKey": string;
        /**
          * The number of rows to display per page
         */
        "limit": number;
        /**
          * The uuid of the subscription that you want to display invoices for.
         */
        "subscriptionUuid": string;
    }
    interface SalableStatus {
        /**
          * The status type
         */
        "statusType": StatusType;
    }
}
declare global {
    /**
     * button component
     */
    interface HTMLSalableButtonElement extends Components.SalableButton, HTMLStencilElement {
    }
    var HTMLSalableButtonElement: {
        prototype: HTMLSalableButtonElement;
        new (): HTMLSalableButtonElement;
    };
    interface HTMLSalableDateElement extends Components.SalableDate, HTMLStencilElement {
    }
    var HTMLSalableDateElement: {
        prototype: HTMLSalableDateElement;
        new (): HTMLSalableDateElement;
    };
    interface HTMLSalableInvoicesElement extends Components.SalableInvoices, HTMLStencilElement {
    }
    var HTMLSalableInvoicesElement: {
        prototype: HTMLSalableInvoicesElement;
        new (): HTMLSalableInvoicesElement;
    };
    interface HTMLSalableStatusElement extends Components.SalableStatus, HTMLStencilElement {
    }
    var HTMLSalableStatusElement: {
        prototype: HTMLSalableStatusElement;
        new (): HTMLSalableStatusElement;
    };
    interface HTMLElementTagNameMap {
        "salable-button": HTMLSalableButtonElement;
        "salable-date": HTMLSalableDateElement;
        "salable-invoices": HTMLSalableInvoicesElement;
        "salable-status": HTMLSalableStatusElement;
    }
}
declare namespace LocalJSX {
    /**
     * button component
     */
    interface SalableButton {
    }
    interface SalableDate {
        /**
          * The date to display
         */
        "date"?: string | number;
    }
    interface SalableInvoices {
        /**
          * The publishable api key, this can be generated in the Salable dashboard
         */
        "apiKey"?: string;
        /**
          * The number of rows to display per page
         */
        "limit"?: number;
        /**
          * The uuid of the subscription that you want to display invoices for.
         */
        "subscriptionUuid"?: string;
    }
    interface SalableStatus {
        /**
          * The status type
         */
        "statusType"?: StatusType;
    }
    interface IntrinsicElements {
        "salable-button": SalableButton;
        "salable-date": SalableDate;
        "salable-invoices": SalableInvoices;
        "salable-status": SalableStatus;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * button component
             */
            "salable-button": LocalJSX.SalableButton & JSXBase.HTMLAttributes<HTMLSalableButtonElement>;
            "salable-date": LocalJSX.SalableDate & JSXBase.HTMLAttributes<HTMLSalableDateElement>;
            "salable-invoices": LocalJSX.SalableInvoices & JSXBase.HTMLAttributes<HTMLSalableInvoicesElement>;
            "salable-status": LocalJSX.SalableStatus & JSXBase.HTMLAttributes<HTMLSalableStatusElement>;
        }
    }
}
